name: T2 Build

on:
  workflow_dispatch:

jobs:
  build:
    name: build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk:
          - 24.10.0
        arch:
          - aarch64_cortex-a53
          - x86_64

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
